name: "Build neovim-pyinstaller wheels"

on:
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build Linux wheels
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Compile Neovim and build wheel
        uses: docker://quay.io/pypa/manylinux_2_24_x86_64:latest
        with:
          args: 'make bootstrap build'

      - name: Upload built wheel as job artifact
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0  # We're uploading a zip; no need to try to compress the zip
          if-no-files-found: error
          name: neovim_pyinstaller
          path: 'dist/*.whl'
