name: "Build neovim-pyinstaller wheels"

on:
  workflow_dispatch:

jobs:
  build-wheels:
    name: Build Linux wheels
    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.8"
          # - "3.9"
          # - "3.10"
          # - "3.11"
          # - "3.12"
          # - "3.13"
          # - "3.14"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Compile Neovim and build wheel
        uses: docker://quay.io/pypa/manylinux_2_24_x86_64:latest
        with:
          args: 'make build'

      - name: Upload built wheel as job artifact
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0  # We're uploading a zip; no need to try to compress the zip
          if-no-files-found: error
          name: neovim_pyinstalled py${{ matrix.python_version }}
          path: 'dist/*.whl'
